#!/usr/bin/env sh

if [ $# != 1 ]; then
    echo "Error: 引数が不正です"
    exit 0;
fi

readonly BRANCH_NAME=$1
readonly SRC_DIR="src\/"

readonly REMOVE_SRC=$(echo $BRANCH_NAME | sed -e "s/${SRC_DIR}//g")

# join with a hyphen
readonly JOIN_HYPHEN=$(echo $REMOVE_SRC | sed -e "s/\//-/g")
readonly REMOVE_INDEX_JS=$(echo $JOIN_HYPHEN | sed -e "s/-index.js//g")
readonly REMOVE_JS=$(echo $REMOVE_INDEX_JS | sed -e "s/.js//g")

readonly NEW_BRANCH_NAME="js2ts/$REMOVE_JS"

# Enterなら実行
read -n1 -p "$NEW_BRANCH_NAME へgit checkoutしますか? (Enter / n): " INPUT_VALUE
if [ ! -z $INPUT_VALUE ]; then
  echo '\n中断しました'
  exit
fi

# switching branch
git checkout -b $NEW_BRANCH_NAME
